export default {
    GET_ALL_IMAGE: 'GET_ALL_IMAGE',
    GET_ALL_IMAGE_REQUEST: 'GET_ALL_IMAGE_REQUEST',
    GET_ALL_IMAGE_RESPONSE: 'GET_ALL_IMAGE_RESPONSE',
    GET_ALL_IMAGE_ERROR: 'GET_ALL_IMAGE_ERROR',
}


